# Generated by Django 5.2.5 on 2026-05-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Pedido', models.CharField()),
                ('Nombre_Pedido', models.CharField()),
                ('Categoria_Pedido', models.CharField()),
                ('Mesa_Pedido', models.CharField()),
                ('Fecha_Pedido', models.DateField()),
                ('Hora_Pedido', models.TimeField()),
            ],
        ),
    ]
