# Generated by Django 5.2.5 on 2026-05-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_Ven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Ventas', models.CharField()),
                ('Nombre_Ventas', models.CharField()),
                ('Mesa_Ventas', models.CharField()),
                ('Monto_Ventas', models.CharField()),
                ('Metodo_Ventas', models.CharField()),
                ('Fecha_Ventas', models.DateField()),
                ('Hora_Ventas', models.TimeField()),
            ],
        ),
    ]
