# Generated by Django 5.2.5 on 2026-05-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_tabla_ven'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Empleado', models.CharField()),
                ('Nombre_Empleado', models.CharField()),
                ('Cargo_Empleado', models.CharField()),
                ('Numero_Empleado', models.CharField()),
                ('Ubicacion_Empleado', models.CharField()),
                ('Correo_Empleado', models.CharField()),
                ('Tiempo_Contrato_Empleado', models.CharField()),
            ],
        ),
    ]
