# Generated by Django 5.2.5 on 2026-05-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_tabla_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Horario', models.CharField()),
                ('Nombre_Horario', models.CharField()),
                ('Fecha_Horario', models.DateField()),
                ('Hora_Inicio_Horario', models.TimeField()),
                ('Hora_Final_Horario', models.TimeField()),
                ('Comentario_Horario', models.CharField()),
            ],
        ),
    ]
