# Generated by Django 5.2.5 on 2026-05-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_tabla_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Usuario', models.CharField()),
                ('Nombre_Usuario', models.CharField()),
                ('Contrasenia_Usuario', models.CharField()),
                ('Fecha_Creacion_Usuario', models.DateField()),
                ('Hora_Creacion_Usuario', models.TimeField()),
                ('Comentario_Usuario', models.CharField()),
            ],
        ),
    ]
